services:
  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    networks:
      operator-network:
        aliases:
          - registry
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - operator-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - operator-network
    depends_on:
      - postgres
    restart: unless-stopped

  operator-builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - operator-network
    privileged: true
    depends_on:
      registry:
        condition: service_healthy
    extra_hosts:
      - "registry:127.0.0.1"
    command: /bin/bash -c "
      sleep 5 && 
      curl -f http://registry:5000/v2/ || exit 1 &&
      ./scripts/kind-setup.sh"

volumes:
  registry-data:
  pg-data:

networks:
  operator-network:
    driver: bridge
    name: operator-network