kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: $(pwd)/local-storage
    containerPath: /data
  extraPortMappings:
  - containerPort: 5432
    hostPort: 5432
    protocol: TCP