apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-operator-controller-manager
  namespace: postgres-operator-system
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/component: controller