apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: postgres-operator-manager
  namespace: postgres-operator-system