---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.example.com
  resources:
  - postgresbackups
  - postgresclusters
  - postgresrestores
  - postgresusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.example.com
  resources:
  - postgresbackups/finalizers
  - postgresclusters/finalizers
  - postgresrestores/finalizers
  - postgresusers/finalizers
  verbs:
  - update
- apiGroups:
  - database.example.com
  resources:
  - postgresbackups/status
  - postgresclusters/status
  - postgresrestores/status
  - postgresusers/status
  verbs:
  - get
  - patch
  - update
