apiVersion: database.example.com/v1
kind: PostgresBackup
metadata:
  name: pg-backup-local
spec:
  clusterRef:
    name: pg-cluster-local
  type: "full"
  storage:
    type: "local"
    config:
      path: "/mnt/postgres-backups"
      # node: "node-1"
  retentionPolicy:
    keepLast: 7
    keepDaily: 30
    keepWeekly: 12 
    deleteOnClusterDeletion: true
  options:
    compression: 6
    encryption:
      enabled: false
    parallelJobs: 2
    timeout: "1h"
  includeInstanceConfig: true