apiVersion: database.example.com/v1
kind: PostgresCluster
metadata:
  name: pg-cluster-local
  labels:
    app.kubernetes.io/name: postgrescluster
    app.kubernetes.io/instance: pg-cluster-local
spec:
  postgresVersion: "14"
  replicas: 3
  storage:
    size: "10Gi"
    storageClass: "local-path"
    accessModes: ["ReadWriteOnce"]
  resources:
    cpu: "500m"
    memory: "1Gi"
  backup:
    enabled: true
    schedule: "0 0 * * *"
    retentionPolicy: "7d"
    storage:
      type: "local"
      config:
        path: "/mnt/postgres-backups"
  instances:
    - name: "primary"
      role: "primary"
      storage:
        size: "10Gi"
        storageClass: "local-path"
        accessModes: ["ReadWriteOnce"]
      config:
        shared_buffers: "1GB"
        work_mem: "32MB"
    - name: "replica-1"
      role: "replica"
      replicas: 1
      resources:
        cpu: "250m"
        memory: "512Mi"
  database:
    name: "appdb"
    initScript: |
      CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
      CREATE ROLE readonly;
    access:
      - username: "app_user"
        privileges: ["SELECT", "INSERT", "UPDATE"]
      - username: "reporting_user"
        privileges: ["SELECT"]
        schemas:
          - name: "reporting"
            privileges: ["SELECT"]
  highAvailability:
    enabled: true
    synchronousReplication: true
    failoverTimeout: 30
  monitoring:
    enabled: true
    prometheus:
      enabled: true
      port: 9187
      path: "/metrics"