apiVersion: database.example.com/v1
kind: PostgresCluster
metadata:
  name: example-cluster
spec:
  replicas: 3
  postgresVersion: "14"
  storage:
    size: 10Gi
    storageClass: standard
  backup:
    enabled: true
    schedule: "0 0 * * *"
    retention: "30d"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi