apiVersion: database.example.com/v1
kind: PostgresCluster
metadata:
  name: example-cluster
spec:
  replicas: 3
  postgresVersion: "14"
  storage:
    size: 10Gi
    storageClass: standard
  backup:
    enabled: true
    schedule: "0 0 * * *"
    retentionPolicy: "30d"
    storage:
      type: s3
      config: 
        bucket: "my-backup-bucket"
        endpoint: "s3.amazonaws.com"
        region: "us-east-1"
        secretName: "s3-credentials"
  resources:
    cpu: 500m
    memory: 1Gi