apiVersion: database.example.com/v1
kind: PostgresBackup
metadata:
  name: example-backup
spec:
  clusterRef:
    name: example-cluster
  type: "full"
  storage:
    type: "local"
    config: 
      bucket: "my-backup-bucket"
      endpoint: "s3.amazonaws.com"
      region: "us-east-1"
      secretName: "s3-credentials"
  retentionPolicy:
    keepLast: 5