apiVersion: database.example.com/v1
kind: PostgresUser
metadata:
  name: pg-user-local
spec:
  clusterRef:
    name: pg-cluster-local
    namespace: default
  username: "app_user"
  password:
    generate: true
    length: 16
    rotationPolicy:
      enabled: true
      interval: 720
    secretRef:
      name: pg-user-secret 
      key: password     
  connectionLimit: 10       
  privileges:
    - "CREATEDB"           