apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/postgres-operator.clusterserviceversion.yaml

namePrefix: postgres-operator-

labels:
- pairs: 
    operators.coreos.com/postgres-operator.postgres-operator-system: ""

images:
  - name: controller
    newName: localhost:5000/postgres-operator
    newTag: latest